/*
 * Copyright 2016 Davide Maestroni
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.github.dm.jrt.android.channel;

import com.github.dm.jrt.android.channel.builder.AndroidChannelHandler;
import com.github.dm.jrt.android.channel.io.ParcelableByteChannel;
import com.github.dm.jrt.android.channel.io.ParcelableByteChannel.ParcelableByteChunk;
import com.github.dm.jrt.android.channel.io.ParcelableByteChannel
    .ParcelableByteChunkOutputStreamBuilder;
import com.github.dm.jrt.channel.io.ByteChannel.ByteChunkInputStream;
import com.github.dm.jrt.core.executor.ScheduledExecutor;
import com.github.dm.jrt.core.util.ConstantConditions;

import org.jetbrains.annotations.NotNull;

import static com.github.dm.jrt.core.executor.ScheduledExecutors.defaultExecutor;

/**
 * Utility class for handling routine channels.
 * <p>
 * Created by davide-maestroni on 06/18/2015.
 */
public class JRoutineAndroidChannels {

  /**
   * Avoid explicit instantiation.
   */
  protected JRoutineAndroidChannels() {
    ConstantConditions.avoid();
  }

  /**
   * Returns a channel handler employing the default executor.
   *
   * @return the handler instance.
   */
  @NotNull
  public static AndroidChannelHandler channelHandler() {
    return channelHandlerOn(defaultExecutor());
  }

  /**
   * Returns a channel handler employing the specified executor.
   *
   * @param executor the executor instance.
   * @return the handler instance.
   */
  @NotNull
  public static AndroidChannelHandler channelHandlerOn(@NotNull final ScheduledExecutor executor) {
    return new DefaultAndroidChannelHandler(executor);
  }

  /**
   * Creates an input stream returning the concatenation of the data contained in the specified
   * chunks.
   * <p>
   * Note that only one input stream can be created for each chunk.
   *
   * @param chunks the byte chunks whose data have to be concatenated.
   * @return the input stream.
   * @throws java.lang.IllegalStateException if an input stream has been already created for one
   *                                         of the specified chunks.
   */
  @NotNull
  public static ByteChunkInputStream parcelableInputStream(
      @NotNull final Iterable<? extends ParcelableByteChunk> chunks) {
    return ParcelableByteChannel.parcelableInputStream(chunks);
  }

  /**
   * Creates an input stream returning the data contained in the specified chunk.
   * <p>
   * Note that only one input stream can be created for each chunk.
   *
   * @param chunk the byte chunk.
   * @return the input stream.
   * @throws java.lang.IllegalStateException if an input stream has been already created for the
   *                                         specified chunk.
   */
  @NotNull
  public static ByteChunkInputStream parcelableInputStream(
      @NotNull final ParcelableByteChunk chunk) {
    return ParcelableByteChannel.parcelableInputStream(chunk);
  }

  /**
   * Creates an input stream returning the concatenation of the data contained in the specified
   * chunks.
   * <p>
   * Note that only one input stream can be created for each chunk.
   *
   * @param chunks the byte chunks whose data have to be concatenated.
   * @return the input stream.
   * @throws java.lang.IllegalStateException if an input stream has been already created for one
   *                                         of the specified chunks.
   */
  @NotNull
  public static ByteChunkInputStream parcelableInputStream(
      @NotNull final ParcelableByteChunk... chunks) {
    return ParcelableByteChannel.parcelableInputStream(chunks);
  }

  /**
   * Returns a builder of chunk output streams.
   * <br>
   * Since the byte chunks generated by the channel are likely to be part of a remote procedure
   * call, be aware of the limits imposed by the Android OS architecture when choosing a specific
   * chunk size (see {@link android.os.TransactionTooLargeException}).
   * <p>
   * The built streams will not close the underlying channel by default.
   *
   * @return the output stream builder.
   */
  @NotNull
  public static ParcelableByteChunkOutputStreamBuilder parcelableOutputStream() {
    return ParcelableByteChannel.parcelableOutputStream();
  }
}
